package com.treefinance.saas.console.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AppCallbackConfig implements Serializable {
    private Integer id;

    private String appId;

    private String receiver;

    private Byte version;

    private Byte isNewKey;

    private String url;

    private Byte retryTimes;

    private Byte timeOut;

    private String remark;

    private Byte isNotifyCancel;

    private Byte isNotifyFailure;

    private Byte isNotifySuccess;

    private Byte notifyModel;

    private Byte dataType;

    private Date createTime;

    private Date lastUpdateTime;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.Id
     *
     * @return the value of app_callback_config.Id
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.Id
     *
     * @param id the value for app_callback_config.Id
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.AppId
     *
     * @return the value of app_callback_config.AppId
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.AppId
     *
     * @param appId the value for app_callback_config.AppId
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.receiver
     *
     * @return the value of app_callback_config.receiver
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.receiver
     *
     * @param receiver the value for app_callback_config.receiver
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.version
     *
     * @return the value of app_callback_config.version
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.version
     *
     * @param version the value for app_callback_config.version
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setVersion(Byte version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.isNewKey
     *
     * @return the value of app_callback_config.isNewKey
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getIsNewKey() {
        return isNewKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.isNewKey
     *
     * @param isNewKey the value for app_callback_config.isNewKey
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setIsNewKey(Byte isNewKey) {
        this.isNewKey = isNewKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.Url
     *
     * @return the value of app_callback_config.Url
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.Url
     *
     * @param url the value for app_callback_config.Url
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.retryTimes
     *
     * @return the value of app_callback_config.retryTimes
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getRetryTimes() {
        return retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.retryTimes
     *
     * @param retryTimes the value for app_callback_config.retryTimes
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setRetryTimes(Byte retryTimes) {
        this.retryTimes = retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.timeOut
     *
     * @return the value of app_callback_config.timeOut
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.timeOut
     *
     * @param timeOut the value for app_callback_config.timeOut
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setTimeOut(Byte timeOut) {
        this.timeOut = timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.remark
     *
     * @return the value of app_callback_config.remark
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.remark
     *
     * @param remark the value for app_callback_config.remark
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.isNotifyCancel
     *
     * @return the value of app_callback_config.isNotifyCancel
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getIsNotifyCancel() {
        return isNotifyCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.isNotifyCancel
     *
     * @param isNotifyCancel the value for app_callback_config.isNotifyCancel
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setIsNotifyCancel(Byte isNotifyCancel) {
        this.isNotifyCancel = isNotifyCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.isNotifyFailure
     *
     * @return the value of app_callback_config.isNotifyFailure
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getIsNotifyFailure() {
        return isNotifyFailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.isNotifyFailure
     *
     * @param isNotifyFailure the value for app_callback_config.isNotifyFailure
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setIsNotifyFailure(Byte isNotifyFailure) {
        this.isNotifyFailure = isNotifyFailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.isNotifySuccess
     *
     * @return the value of app_callback_config.isNotifySuccess
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getIsNotifySuccess() {
        return isNotifySuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.isNotifySuccess
     *
     * @param isNotifySuccess the value for app_callback_config.isNotifySuccess
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setIsNotifySuccess(Byte isNotifySuccess) {
        this.isNotifySuccess = isNotifySuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.notifyModel
     *
     * @return the value of app_callback_config.notifyModel
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getNotifyModel() {
        return notifyModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.notifyModel
     *
     * @param notifyModel the value for app_callback_config.notifyModel
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setNotifyModel(Byte notifyModel) {
        this.notifyModel = notifyModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.dataType
     *
     * @return the value of app_callback_config.dataType
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Byte getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.dataType
     *
     * @param dataType the value for app_callback_config.dataType
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setDataType(Byte dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.CreateTime
     *
     * @return the value of app_callback_config.CreateTime
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.CreateTime
     *
     * @param createTime the value for app_callback_config.CreateTime
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config.LastUpdateTime
     *
     * @return the value of app_callback_config.LastUpdateTime
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_callback_config.LastUpdateTime
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Oct 11 09:37:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", receiver=").append(receiver);
        sb.append(", version=").append(version);
        sb.append(", isNewKey=").append(isNewKey);
        sb.append(", url=").append(url);
        sb.append(", retryTimes=").append(retryTimes);
        sb.append(", timeOut=").append(timeOut);
        sb.append(", remark=").append(remark);
        sb.append(", isNotifyCancel=").append(isNotifyCancel);
        sb.append(", isNotifyFailure=").append(isNotifyFailure);
        sb.append(", isNotifySuccess=").append(isNotifySuccess);
        sb.append(", notifyModel=").append(notifyModel);
        sb.append(", dataType=").append(dataType);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}