package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.AppCallbackConfigBackup;
import com.treefinance.saas.management.console.dao.entity.AppCallbackConfigBackupCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppCallbackConfigBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    long countByExample(AppCallbackConfigBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int deleteByExample(AppCallbackConfigBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int insert(AppCallbackConfigBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int insertSelective(AppCallbackConfigBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    List<AppCallbackConfigBackup> selectByExampleWithRowbounds(AppCallbackConfigBackupCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    List<AppCallbackConfigBackup> selectByExample(AppCallbackConfigBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    List<AppCallbackConfigBackup> selectPaginationByExample(AppCallbackConfigBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    void batchInsert(List<AppCallbackConfigBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    void batchUpdateByPrimaryKey(List<AppCallbackConfigBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<AppCallbackConfigBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    AppCallbackConfigBackup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppCallbackConfigBackup record, @Param("example") AppCallbackConfigBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByExample(@Param("record") AppCallbackConfigBackup record, @Param("example") AppCallbackConfigBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByPrimaryKeySelective(AppCallbackConfigBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByPrimaryKey(AppCallbackConfigBackup record);
}