package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.AppLicense;
import com.treefinance.saas.management.console.dao.entity.AppLicenseCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppLicenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int countByExample(AppLicenseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int deleteByExample(AppLicenseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int insert(AppLicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int insertSelective(AppLicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    List<AppLicense> selectByExampleWithRowbounds(AppLicenseCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    List<AppLicense> selectByExample(AppLicenseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    AppLicense selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppLicense record, @Param("example") AppLicenseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int updateByExample(@Param("record") AppLicense record, @Param("example") AppLicenseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int updateByPrimaryKeySelective(AppLicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbggenerated Wed Jun 21 15:58:52 CST 2017
     */
    int updateByPrimaryKey(AppLicense record);
}