package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.AppLicenseBackup;
import com.treefinance.saas.management.console.dao.entity.AppLicenseBackupCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppLicenseBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    long countByExample(AppLicenseBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int deleteByExample(AppLicenseBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int insert(AppLicenseBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int insertSelective(AppLicenseBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    List<AppLicenseBackup> selectByExampleWithRowbounds(AppLicenseBackupCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    List<AppLicenseBackup> selectByExample(AppLicenseBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    List<AppLicenseBackup> selectPaginationByExample(AppLicenseBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    void batchInsert(List<AppLicenseBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    void batchUpdateByPrimaryKey(List<AppLicenseBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<AppLicenseBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    AppLicenseBackup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppLicenseBackup record, @Param("example") AppLicenseBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByExample(@Param("record") AppLicenseBackup record, @Param("example") AppLicenseBackupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByPrimaryKeySelective(AppLicenseBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    int updateByPrimaryKey(AppLicenseBackup record);
}