package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.BizLicenseType;
import com.treefinance.saas.management.console.dao.entity.BizLicenseTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BizLicenseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    long countByExample(BizLicenseTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int deleteByExample(BizLicenseTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int insert(BizLicenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int insertSelective(BizLicenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    List<BizLicenseType> selectByExampleWithRowbounds(BizLicenseTypeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    List<BizLicenseType> selectByExample(BizLicenseTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    List<BizLicenseType> selectPaginationByExample(BizLicenseTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int insertOrUpdateBySelective(BizLicenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    void batchInsert(List<BizLicenseType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    void batchUpdateByPrimaryKey(List<BizLicenseType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<BizLicenseType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    BizLicenseType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") BizLicenseType record, @Param("example") BizLicenseTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int updateByExample(@Param("record") BizLicenseType record, @Param("example") BizLicenseTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int updateByPrimaryKeySelective(BizLicenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Mon Jul 03 14:41:15 CST 2017
     */
    int updateByPrimaryKey(BizLicenseType record);
}