package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.ConsoleUser;
import com.treefinance.saas.management.console.dao.entity.ConsoleUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConsoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    long countByExample(ConsoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int deleteByExample(ConsoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int insert(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int insertSelective(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    List<ConsoleUser> selectByExampleWithRowbounds(ConsoleUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    List<ConsoleUser> selectByExample(ConsoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    List<ConsoleUser> selectPaginationByExample(ConsoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int insertOrUpdateBySelective(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    void batchInsert(List<ConsoleUser> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    void batchUpdateByPrimaryKey(List<ConsoleUser> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<ConsoleUser> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    ConsoleUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") ConsoleUser record, @Param("example") ConsoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int updateByExample(@Param("record") ConsoleUser record, @Param("example") ConsoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int updateByPrimaryKeySelective(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    int updateByPrimaryKey(ConsoleUser record);
}