package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.MerchantBase;
import com.treefinance.saas.management.console.dao.entity.MerchantBaseCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int countByExample(MerchantBaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int deleteByExample(MerchantBaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int insert(MerchantBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int insertSelective(MerchantBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    List<MerchantBase> selectByExampleWithRowbounds(MerchantBaseCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    List<MerchantBase> selectByExample(MerchantBaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    MerchantBase selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantBase record, @Param("example") MerchantBaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int updateByExample(@Param("record") MerchantBase record, @Param("example") MerchantBaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 21 16:02:57 CST 2017
     */
    int updateByPrimaryKey(MerchantBase record);
}