package com.treefinance.saas.management.console.dao.mapper;

import com.treefinance.saas.management.console.dao.entity.Task;
import com.treefinance.saas.management.console.dao.entity.TaskCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    long countByExample(TaskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int deleteByExample(TaskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    List<Task> selectByExampleWithRowbounds(TaskCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    List<Task> selectByExample(TaskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    List<Task> selectPaginationByExample(TaskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    void batchInsert(List<Task> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    void batchUpdateByPrimaryKey(List<Task> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<Task> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int updateByExample(@Param("record") Task record, @Param("example") TaskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    int updateByPrimaryKey(Task record);
}