package com.treefinance.saas.management.console.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AppCallbackConfigBackup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_config_backup.Id
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_config_backup.callBackConfigId
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Integer callBackConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_config_backup.DataSecretKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String dataSecretKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_config_backup.CreateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_config_backup.LastUpdateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config_backup.Id
     *
     * @return the value of app_callback_config_backup.Id
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config_backup.Id
     *
     * @param id the value for app_callback_config_backup.Id
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config_backup.callBackConfigId
     *
     * @return the value of app_callback_config_backup.callBackConfigId
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Integer getCallBackConfigId() {
        return callBackConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config_backup.callBackConfigId
     *
     * @param callBackConfigId the value for app_callback_config_backup.callBackConfigId
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setCallBackConfigId(Integer callBackConfigId) {
        this.callBackConfigId = callBackConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config_backup.DataSecretKey
     *
     * @return the value of app_callback_config_backup.DataSecretKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getDataSecretKey() {
        return dataSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config_backup.DataSecretKey
     *
     * @param dataSecretKey the value for app_callback_config_backup.DataSecretKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setDataSecretKey(String dataSecretKey) {
        this.dataSecretKey = dataSecretKey == null ? null : dataSecretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config_backup.CreateTime
     *
     * @return the value of app_callback_config_backup.CreateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config_backup.CreateTime
     *
     * @param createTime the value for app_callback_config_backup.CreateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_config_backup.LastUpdateTime
     *
     * @return the value of app_callback_config_backup.LastUpdateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_config_backup.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_callback_config_backup.LastUpdateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", callBackConfigId=").append(callBackConfigId);
        sb.append(", dataSecretKey=").append(dataSecretKey);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}