package com.treefinance.saas.management.console.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AppLicenseBackup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.Id
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.AppId
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.SdkPublicKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String sdkPublicKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.SdkPrivateKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String sdkPrivateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.ServerPublicKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String serverPublicKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.ServerPrivateKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String serverPrivateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.DataSecretKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private String dataSecretKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.CreateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_license_backup.LastUpdateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.Id
     *
     * @return the value of app_license_backup.Id
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.Id
     *
     * @param id the value for app_license_backup.Id
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.AppId
     *
     * @return the value of app_license_backup.AppId
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.AppId
     *
     * @param appId the value for app_license_backup.AppId
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.SdkPublicKey
     *
     * @return the value of app_license_backup.SdkPublicKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getSdkPublicKey() {
        return sdkPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.SdkPublicKey
     *
     * @param sdkPublicKey the value for app_license_backup.SdkPublicKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setSdkPublicKey(String sdkPublicKey) {
        this.sdkPublicKey = sdkPublicKey == null ? null : sdkPublicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.SdkPrivateKey
     *
     * @return the value of app_license_backup.SdkPrivateKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getSdkPrivateKey() {
        return sdkPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.SdkPrivateKey
     *
     * @param sdkPrivateKey the value for app_license_backup.SdkPrivateKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setSdkPrivateKey(String sdkPrivateKey) {
        this.sdkPrivateKey = sdkPrivateKey == null ? null : sdkPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.ServerPublicKey
     *
     * @return the value of app_license_backup.ServerPublicKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getServerPublicKey() {
        return serverPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.ServerPublicKey
     *
     * @param serverPublicKey the value for app_license_backup.ServerPublicKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setServerPublicKey(String serverPublicKey) {
        this.serverPublicKey = serverPublicKey == null ? null : serverPublicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.ServerPrivateKey
     *
     * @return the value of app_license_backup.ServerPrivateKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getServerPrivateKey() {
        return serverPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.ServerPrivateKey
     *
     * @param serverPrivateKey the value for app_license_backup.ServerPrivateKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setServerPrivateKey(String serverPrivateKey) {
        this.serverPrivateKey = serverPrivateKey == null ? null : serverPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.DataSecretKey
     *
     * @return the value of app_license_backup.DataSecretKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getDataSecretKey() {
        return dataSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.DataSecretKey
     *
     * @param dataSecretKey the value for app_license_backup.DataSecretKey
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setDataSecretKey(String dataSecretKey) {
        this.dataSecretKey = dataSecretKey == null ? null : dataSecretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.CreateTime
     *
     * @return the value of app_license_backup.CreateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.CreateTime
     *
     * @param createTime the value for app_license_backup.CreateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_license_backup.LastUpdateTime
     *
     * @return the value of app_license_backup.LastUpdateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_license_backup.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_license_backup.LastUpdateTime
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", sdkPublicKey=").append(sdkPublicKey);
        sb.append(", sdkPrivateKey=").append(sdkPrivateKey);
        sb.append(", serverPublicKey=").append(serverPublicKey);
        sb.append(", serverPrivateKey=").append(serverPrivateKey);
        sb.append(", dataSecretKey=").append(dataSecretKey);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}