package com.treefinance.saas.management.console.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppLicenseBackupCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected int limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected int offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public AppLicenseBackupCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setLimit(int limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setOffset(int offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("AppId is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("AppId is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("AppId =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("AppId <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("AppId >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("AppId >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("AppId <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("AppId <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("AppId like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("AppId not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("AppId in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("AppId not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("AppId between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("AppId not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyIsNull() {
            addCriterion("SdkPublicKey is null");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyIsNotNull() {
            addCriterion("SdkPublicKey is not null");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyEqualTo(String value) {
            addCriterion("SdkPublicKey =", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyNotEqualTo(String value) {
            addCriterion("SdkPublicKey <>", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyGreaterThan(String value) {
            addCriterion("SdkPublicKey >", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyGreaterThanOrEqualTo(String value) {
            addCriterion("SdkPublicKey >=", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyLessThan(String value) {
            addCriterion("SdkPublicKey <", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyLessThanOrEqualTo(String value) {
            addCriterion("SdkPublicKey <=", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyLike(String value) {
            addCriterion("SdkPublicKey like", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyNotLike(String value) {
            addCriterion("SdkPublicKey not like", value, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyIn(List<String> values) {
            addCriterion("SdkPublicKey in", values, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyNotIn(List<String> values) {
            addCriterion("SdkPublicKey not in", values, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyBetween(String value1, String value2) {
            addCriterion("SdkPublicKey between", value1, value2, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPublicKeyNotBetween(String value1, String value2) {
            addCriterion("SdkPublicKey not between", value1, value2, "sdkPublicKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyIsNull() {
            addCriterion("SdkPrivateKey is null");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyIsNotNull() {
            addCriterion("SdkPrivateKey is not null");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyEqualTo(String value) {
            addCriterion("SdkPrivateKey =", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyNotEqualTo(String value) {
            addCriterion("SdkPrivateKey <>", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyGreaterThan(String value) {
            addCriterion("SdkPrivateKey >", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyGreaterThanOrEqualTo(String value) {
            addCriterion("SdkPrivateKey >=", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyLessThan(String value) {
            addCriterion("SdkPrivateKey <", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyLessThanOrEqualTo(String value) {
            addCriterion("SdkPrivateKey <=", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyLike(String value) {
            addCriterion("SdkPrivateKey like", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyNotLike(String value) {
            addCriterion("SdkPrivateKey not like", value, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyIn(List<String> values) {
            addCriterion("SdkPrivateKey in", values, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyNotIn(List<String> values) {
            addCriterion("SdkPrivateKey not in", values, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyBetween(String value1, String value2) {
            addCriterion("SdkPrivateKey between", value1, value2, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andSdkPrivateKeyNotBetween(String value1, String value2) {
            addCriterion("SdkPrivateKey not between", value1, value2, "sdkPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyIsNull() {
            addCriterion("ServerPublicKey is null");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyIsNotNull() {
            addCriterion("ServerPublicKey is not null");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyEqualTo(String value) {
            addCriterion("ServerPublicKey =", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyNotEqualTo(String value) {
            addCriterion("ServerPublicKey <>", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyGreaterThan(String value) {
            addCriterion("ServerPublicKey >", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyGreaterThanOrEqualTo(String value) {
            addCriterion("ServerPublicKey >=", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyLessThan(String value) {
            addCriterion("ServerPublicKey <", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyLessThanOrEqualTo(String value) {
            addCriterion("ServerPublicKey <=", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyLike(String value) {
            addCriterion("ServerPublicKey like", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyNotLike(String value) {
            addCriterion("ServerPublicKey not like", value, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyIn(List<String> values) {
            addCriterion("ServerPublicKey in", values, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyNotIn(List<String> values) {
            addCriterion("ServerPublicKey not in", values, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyBetween(String value1, String value2) {
            addCriterion("ServerPublicKey between", value1, value2, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPublicKeyNotBetween(String value1, String value2) {
            addCriterion("ServerPublicKey not between", value1, value2, "serverPublicKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyIsNull() {
            addCriterion("ServerPrivateKey is null");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyIsNotNull() {
            addCriterion("ServerPrivateKey is not null");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyEqualTo(String value) {
            addCriterion("ServerPrivateKey =", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyNotEqualTo(String value) {
            addCriterion("ServerPrivateKey <>", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyGreaterThan(String value) {
            addCriterion("ServerPrivateKey >", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyGreaterThanOrEqualTo(String value) {
            addCriterion("ServerPrivateKey >=", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyLessThan(String value) {
            addCriterion("ServerPrivateKey <", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyLessThanOrEqualTo(String value) {
            addCriterion("ServerPrivateKey <=", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyLike(String value) {
            addCriterion("ServerPrivateKey like", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyNotLike(String value) {
            addCriterion("ServerPrivateKey not like", value, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyIn(List<String> values) {
            addCriterion("ServerPrivateKey in", values, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyNotIn(List<String> values) {
            addCriterion("ServerPrivateKey not in", values, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyBetween(String value1, String value2) {
            addCriterion("ServerPrivateKey between", value1, value2, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andServerPrivateKeyNotBetween(String value1, String value2) {
            addCriterion("ServerPrivateKey not between", value1, value2, "serverPrivateKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyIsNull() {
            addCriterion("DataSecretKey is null");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyIsNotNull() {
            addCriterion("DataSecretKey is not null");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyEqualTo(String value) {
            addCriterion("DataSecretKey =", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyNotEqualTo(String value) {
            addCriterion("DataSecretKey <>", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyGreaterThan(String value) {
            addCriterion("DataSecretKey >", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyGreaterThanOrEqualTo(String value) {
            addCriterion("DataSecretKey >=", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyLessThan(String value) {
            addCriterion("DataSecretKey <", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyLessThanOrEqualTo(String value) {
            addCriterion("DataSecretKey <=", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyLike(String value) {
            addCriterion("DataSecretKey like", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyNotLike(String value) {
            addCriterion("DataSecretKey not like", value, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyIn(List<String> values) {
            addCriterion("DataSecretKey in", values, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyNotIn(List<String> values) {
            addCriterion("DataSecretKey not in", values, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyBetween(String value1, String value2) {
            addCriterion("DataSecretKey between", value1, value2, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andDataSecretKeyNotBetween(String value1, String value2) {
            addCriterion("DataSecretKey not between", value1, value2, "dataSecretKey");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("LastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("LastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("LastUpdateTime =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("LastUpdateTime <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("LastUpdateTime >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdateTime >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("LastUpdateTime <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdateTime <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("LastUpdateTime in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("LastUpdateTime not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("LastUpdateTime between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdateTime not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_license_backup
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 16 11:24:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_license_backup
     *
     * @mbg.generated Mon Oct 16 11:24:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}