package com.treefinance.saas.management.console.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class BizLicenseType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_license_type.Id
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_license_type.BizType
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    private Byte bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_license_type.BizName
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    private String bizName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_license_type.CreateTime
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_license_type.LastUpdateTime
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_license_type
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_license_type.Id
     *
     * @return the value of biz_license_type.Id
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_license_type.Id
     *
     * @param id the value for biz_license_type.Id
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_license_type.BizType
     *
     * @return the value of biz_license_type.BizType
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public Byte getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_license_type.BizType
     *
     * @param bizType the value for biz_license_type.BizType
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_license_type.BizName
     *
     * @return the value of biz_license_type.BizName
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_license_type.BizName
     *
     * @param bizName the value for biz_license_type.BizName
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_license_type.CreateTime
     *
     * @return the value of biz_license_type.CreateTime
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_license_type.CreateTime
     *
     * @param createTime the value for biz_license_type.CreateTime
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_license_type.LastUpdateTime
     *
     * @return the value of biz_license_type.LastUpdateTime
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_license_type.LastUpdateTime
     *
     * @param lastUpdateTime the value for biz_license_type.LastUpdateTime
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_license_type
     *
     * @mbg.generated Tue Jul 04 10:52:24 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bizType=").append(bizType);
        sb.append(", bizName=").append(bizName);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}