package com.treefinance.saas.management.console.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class ConsoleUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user.Id
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user.LoginName
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user.Password
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user.IsActive
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user.CreateTime
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user.LastUpdateTime
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user.Id
     *
     * @return the value of console_user.Id
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user.Id
     *
     * @param id the value for console_user.Id
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user.LoginName
     *
     * @return the value of console_user.LoginName
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user.LoginName
     *
     * @param loginName the value for console_user.LoginName
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user.Password
     *
     * @return the value of console_user.Password
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user.Password
     *
     * @param password the value for console_user.Password
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user.IsActive
     *
     * @return the value of console_user.IsActive
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user.IsActive
     *
     * @param isActive the value for console_user.IsActive
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user.CreateTime
     *
     * @return the value of console_user.CreateTime
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user.CreateTime
     *
     * @param createTime the value for console_user.CreateTime
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user.LastUpdateTime
     *
     * @return the value of console_user.LastUpdateTime
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user.LastUpdateTime
     *
     * @param lastUpdateTime the value for console_user.LastUpdateTime
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user
     *
     * @mbg.generated Mon Jun 26 20:39:51 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", isActive=").append(isActive);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}