package com.treefinance.saas.management.console.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.Id
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.TaskId
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.Code
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.Msg
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.OccurTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private Date occurTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.ErrorMsg
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private String errorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.CreateTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.LastUpdateTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_log
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.Id
     *
     * @return the value of task_log.Id
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.Id
     *
     * @param id the value for task_log.Id
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.TaskId
     *
     * @return the value of task_log.TaskId
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.TaskId
     *
     * @param taskId the value for task_log.TaskId
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.Code
     *
     * @return the value of task_log.Code
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.Code
     *
     * @param code the value for task_log.Code
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.Msg
     *
     * @return the value of task_log.Msg
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.Msg
     *
     * @param msg the value for task_log.Msg
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.OccurTime
     *
     * @return the value of task_log.OccurTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public Date getOccurTime() {
        return occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.OccurTime
     *
     * @param occurTime the value for task_log.OccurTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setOccurTime(Date occurTime) {
        this.occurTime = occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.ErrorMsg
     *
     * @return the value of task_log.ErrorMsg
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.ErrorMsg
     *
     * @param errorMsg the value for task_log.ErrorMsg
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.CreateTime
     *
     * @return the value of task_log.CreateTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.CreateTime
     *
     * @param createTime the value for task_log.CreateTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.LastUpdateTime
     *
     * @return the value of task_log.LastUpdateTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.LastUpdateTime
     *
     * @param lastUpdateTime the value for task_log.LastUpdateTime
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbg.generated Mon Aug 21 19:08:12 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", code=").append(code);
        sb.append(", msg=").append(msg);
        sb.append(", occurTime=").append(occurTime);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}